5/3/11 6:05:59 PM (thread 0 run 0): Aborted run due to Jython exception: NameError: LoggingEvent [calling TestRunner]
NameError: LoggingEvent
	File "./scribe.py", line 25, in __call__
